#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"
LINK_FILE="LINK"
LINK_FILE_PATH="$DOKKU_ROOT/$APP/$LINK_FILE"

if [[ -f "$LINK_FILE_PATH" ]]; then
  while read line
  do
    output="$output -link $line"
  done < $LINK_FILE_PATH
fi
echo "$STDIN$output"
